import MainLayout from "@/layout/MainLayout";
import "./globals.css";
import { appName } from "@/config/apiUrl";

export const metadata = {
  title:{
    default: appName,
    template:`${appName} | %s`
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body>
        <MainLayout className="mt-16">
          {children}
        </MainLayout>

      </body>
    </html>
  );
}
